language: c

# We need at least Ubuntu 14.04 for the libopus dependency.
dist: trusty

addons:
  apt:
    packages:
      - libogg-dev
      - libopus-dev
      - libopusfile-dev
      - libflac-dev

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install libogg opus opusfile libopusenc flac; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export PKG_CONFIG_PATH="$(brew --prefix openssl)/lib/pkgconfig"; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git clone https://gitlab.xiph.org/xiph/libopusenc.git; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pushd libopusenc; ./autogen.sh; ./configure --prefix=$PWD/_inst; make check; make install; export PKG_CONFIG_PATH=$PWD/_inst/lib/pkgconfig; popd; fi

script:
  - ./autogen.sh
  - ./configure
  - make
  - make distcheck
